name: Github Workflow1

on:
  push:
  workflow_dispatch:
    inputs:
      name:
        description: Name of the person to greet
        required: true
        default: "Ankit Mittal"
      test_level:
        description: Select the test level
        required: true
        type: choice
        options:
          - Default
          - RunAllTests
          - RunLocalTests
        default: "Default"


jobs:

  PrintValues:
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Print Inputs
        run: |
          echo Name is ${{github.event.inputs.name}}
          echo Test level is ${{github.event.inputs.test_level}}
          echo github actor is ${{github.actor}}
        # git status - this will throw error

      - name: Checkout code
        uses: actions/checkout@v4

      - name: run git status after code checkout
        run: |
          git status
          git branch

  jobtwo:
    needs: PrintValues
    runs-on: ubuntu-latest
    steps:
      - name: do random stuff
        run: |
          echo "lets print the github object!"
 