name: Github Workflow1

on:
  workflow_dispatch:
    inputs:
      name:
        description: Name of the person to greet
        required: true
        default: "Ankit Mittal"
      test_level:
        description: Select the test level
        required: true
        type: choice
        options:
          - Default
          - RunAllTests
          - RunLocalTests
        default: "Default"


jobs:
  PrintValues:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Print Inputs
        run: |
          echo Name is ${{github.event.inputs.name}}
          echo Test level is ${{github.event.inputs.test_level}}

      - name: Checkout code
        uses: actions/checkout@v4