name: Github Workflow1

on:
  push:
    branches:
      - main
      - feature/**
    # paths-ignore: is used to ignore the files and folders  
    paths:
      - force-app/**

  workflow_dispatch:
    inputs:
      name:
        description: Name of the person to greet
        required: true
        default: "Ankit Mittal"
      test_level:
        description: Select the test level
        required: true
        type: choice
        options:
          - Default
          - RunAllTests
          - RunLocalTests
        default: "Default"

  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:

  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: run apex test only if PR is raised from uat to main
        if: github.event_name == 'pull_request' && github.event.action == 'opened' && github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'uat'
        run: |
          echo "sample text" >> testfile.txt
          

  PrintValues:
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Print Inputs
        run: |
          echo Name is ${{github.event.inputs.name}}
          echo Test level is ${{github.event.inputs.test_level}}
          echo github actor is ${{github.actor}}
        # git status - this will throw error

      - name: Checkout code
        uses: actions/checkout@v4

      - name: run git status after code checkout
        run: |
          git status
          git branch

  jobtwo:
    needs: PrintValues
    runs-on: ubuntu-latest
    steps:
      - name: do random stuff
        run: |
          echo "lets print the github object!"
 